version: 2
jobs:

  # The build job (lint, test, and build)
  build:
    working_directory: ~/apps/atumo-client
    docker:
      - image: circleci/node:10-browsers
    steps:

      # 1. Checkout the code from the branch into the working_directory
      - checkout

      # 2. Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - add_ssh_keys:
          fingerprints:
            - "66:2c:dd:06:2e:c7:3b:16:9a:bb:62:35:12:0e:a7:68"

      # 3. Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-

      # 4. Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # 5. Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{checksum "package.json"}}
          paths:
            - node_modules/

      # 6. Lint source code
      - run:
          name: Linting
          command: npm run lint

      # 7. Testing source code
      - run:
          name: Testing
          command: npm run test

