version: 2
jobs:
  build:
    working_directory: ~/apps/atumo-client
    docker:
      - image: circleci/node:7.10
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install local dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: run tests
          command: npm run test

      - deploy:
          name: Making deploy
          command: |
            chmod 777 ./scripts/start-app.sh
            ./scripts/start-app.sh
workflows:
  version: 2
  build:
    jobs:
      - "app"